name: Publish Last Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/submit_publish_manifests.ps1
            .github/workflows/generate_publish_manifests.psm1
            .github/workflows/fetch.psm1
            Cargo.toml
          sparse-checkout-cone-mode: false
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Install yq
        run: winget install --id MikeFarah.yq --exact --source winget --accept-package-agreements --accept-source-agreements --disable-interactivity --silent

      - name: Install JSON Schema CLI
        shell: pwsh
        run: |
          $url = "https://github.com/sourcemeta/jsonschema/releases/download/v15.2.0/jsonschema-15.2.0-windows-x86_64.zip"
          $zipFile = "jsonschema.zip"
          $tempDir = "jsonschema_temp"

          Write-Host "Downloading JSON Schema CLI..."
          Invoke-WebRequest -Uri $url -OutFile $zipFile

          Write-Host "Extracting archive..."
          Expand-Archive -Path $zipFile -DestinationPath $tempDir
          Move-Item -Path "$tempDir\jsonschema-15.2.0-windows-x86_64\bin\jsonschema.exe" -Destination "$PWD\jsonschema.exe"

          Remove-Item -Path $zipFile, $tempDir -Recurse -Force
          Write-Host "jsonschema.exe successfully installed to $PWD"

      - name: Run Publish Script
        shell: pwsh
        run: |
          # Note: ADMIN_TOKEN must be a PAT with 'repo' and 'workflow' scopes
          # to allow forking and creating Pull Requests on microsoft/winget-pkgs and ScoopInstaller/Extras
          .github/workflows/submit_publish_manifests.ps1
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
